solo/urls.py
from django.conf.urls import url, patterns, include
from django.contrib.gis import admin
from seller import views


# handler404 = views.handler404
# handler500 = views.handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^buy/', views.buy, name='buy'),
    url(r'^real_estate/', views.real_estate, name='real_estate'),
    url(r'^start_order/$', views.start_order, name='start_order'),
    url(r'^charge/$', views.charge, name="charge"),
	url(r'^login/$', views.login),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
	url(r'^seller/$', views.seller),
	url(r'^about/$', views.about),
	url(r'^accounts/', include('allauth.urls')),
]

seller/forms.py
from datetime import date, datetime

from django import forms
from .models import *


class SellerForm(forms.ModelForm):
	phone = forms.RegexField(regex=r'^\+?1?\d{9,15}$', widget=forms.TextInput(attrs={'required': True, 'class': 'form-control'}), error_messages = {'invalid': "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."}, label="Phone Number")

	class Meta:
		model = Seller
		fields = ['first_name', 'email', 'address', 'phone', 'radius', 'open_hour', 'close_hour', 'operating_days', 'estimated_delivery', 'item', 'unit_price', 'picture', 'description', 'min_order_amount', 'permit_number', 'permit_exp']		
		widgets = {
			'first_name': forms.TextInput(
				attrs={'required': True, 'class': 'form-control'}
			),
			'email': forms.TextInput(
				attrs={'readonly': True, 'class': 'form-control'}
			),
			'address': forms.TextInput(
				attrs={'required': True, 'class': 'form-control', 'placeholder': 'address, city, state, zip'}
			),
			'radius': forms.TextInput(
				attrs={'class': 'form-control'}
			),        
			'open_hour': forms.TextInput(
				attrs={'class': 'form-control'}
			),
			'close_hour': forms.TextInput(
				attrs={'class': 'form-control'}
			),
			'item': forms.TextInput(
				attrs={'required': True, 'class': 'form-control'}
			),            
			'unit_price': forms.TextInput(
				attrs={'required': True, 'class': 'form-control'}
			),
			'description': forms.TextInput(
				attrs={'class': 'form-control'}
			),
			'min_order_amount': forms.TextInput(
				attrs={'class': 'form-control'}
			),
			'permit_number': forms.TextInput(
				attrs={'class': 'form-control',}
			),
			'permit_exp': forms.TextInput(
				attrs={'class': 'form-control'}
			),
			'operating_days': forms.CheckboxSelectMultiple(
				attrs={'class': 'weekday'}
			),
			'estimated_delivery': forms.Select(
				choices=Estimated_Order_to_Delivery,              
				attrs={'required': True, 'class': 'form-control'}
			),
		}
		labels = {
			'first_name': 'Business Name',
			'permit_exp': 'Permit Expiration',
			'unit_price': 'Price in Dollars and Cents',
			'min_order_amount': 'Min Order Quantity of Units',
		}
	
		
class OrderForm(forms.Form):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}), label='Seller Name')
	# email = forms.CharField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}), label='Seller Email')
	# phone = forms.CharField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}), label='Seller Phone')
	distance = forms.CharField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}), label='Distance Away')
	address = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'class': 'form-control'}), label='Customer Location')
	estimated_delivery = forms.CharField(widget=forms.Select(choices=Estimated_Order_to_Delivery,attrs={'readonly': True, 'class': 'form-control', 'disabled': 'disabled'}), label='Estimated Delivery Time')
	
	unit_price = forms.DecimalField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}), label="Unit Price in Dollars and Cents")
	min_order_amount = forms.FloatField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}), label="Min. Quantity of Units")	
	permit_number = forms.CharField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'form-control'}))
	quantity = forms.FloatField(widget=forms.NumberInput(attrs={'required': True, 'class': 'form-control'}), label="Quantity of Units")
	buyer_name = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'class': 'form-control'}), label="Buyer Name")
	buyer_phone = forms.CharField(widget=forms.TextInput(attrs={'required':True, 'class': 'form-control'}), label="Buyer Phone Number:")
	# buyer_phone = forms.RegexField(regex=r'^\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})$', widget=forms.TextInput(attrs={'required': True, 'class': 'form-control'}), error_messages = {'invalid': "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."}, label="Buyer Phone Number")

	def is_valid(self):
		# run the parent validation first
		valid = super(OrderForm, self).is_valid()
		for error in self._errors:
			if error not in ['estimated_delivery', 'unit_price']:
				return False
		return True
			  

seller/views.py
from urllib2 import URLError
from datetime import datetime
import requests
import stripe
import pytz

from django.contrib.gis import geos
from django.contrib.gis import measure
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.forms.models import model_to_dict
from django.conf import settings
from django.core.mail import send_mail
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from twilio.rest import TwilioRestClient 

from geopy.geocoders import GoogleV3, Nominatim
from geopy.exc import GeocoderQueryError

from .forms import *
from .models import *
from allauth.socialaccount.models import *

def get_sellers(location):
	'''
	get open and shortest delivery hour
	get sellers cover the current location and  return then in distance order
	'''
	utc_now = timezone.now()

	# filter workday and time in local time
	sellers_id = []
	for seller in Seller.objects.all():
		if not (seller.time_zone and seller.is_active):
			continue
		local_timezone = pytz.timezone(seller.time_zone)
		local_time = utc_now.astimezone(local_timezone)
		weekday = local_time.isoweekday()

		if seller.operating_days.filter(id=weekday) and local_time.time() > seller.open_hour and local_time.time() < seller.close_hour:
			sellers_id.append(seller.id)

	current_point = geos.fromstr("POINT(%s)" % location)
	dis_sellers = Seller.gis.distance(current_point)
	# sort by estimated delivery time    
	dis_sellers = dis_sellers.filter(id__in=sellers_id).order_by('estimated_delivery') 
	# filter only in radius
	sellers = [seller for seller in dis_sellers if seller.distance.mi <= seller.radius]
	return sellers

def get_sellers_address(location, date_time):
	'''
	get open and shortest delivery hour
	get sellers cover the current location and  return then in distance order
	'''
	utc_now = datetime.strptime(date_time, '%Y/%m/%d %H:%M')
	# filter workday and time in local time
	sellers_id = []
	for seller in Seller.objects.all():
		if not (seller.time_zone and seller.is_active):
			continue
		local_timezone = pytz.timezone(seller.time_zone)
		utc_now = utc_now.replace(tzinfo=local_timezone)
		local_time = utc_now.astimezone(local_timezone)
		weekday = local_time.isoweekday()

		if seller.operating_days.filter(id=weekday) and local_time.time() > seller.open_hour and local_time.time() < seller.close_hour:
			sellers_id.append(seller.id)

	current_point = geos.fromstr("POINT({} {})".format(location.longitude, location.latitude))
	dis_sellers = Seller.gis.distance(current_point)
	# sort by estimated delivery time    
	dis_sellers = dis_sellers.filter(id__in=sellers_id).order_by('estimated_delivery') 
	# filter only in radius
	sellers = [seller for seller in dis_sellers if seller.distance.mi <= seller.radius]
	return sellers

def get_client_ip(request):
	'''
	get ip from the request
	'''
	x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
	if x_forwarded_for:
		ip = x_forwarded_for.split(',')[-1].strip()
	else:
		ip = request.META.get('REMOTE_ADDR')
	return ip

def get_client_location_with_ip(ip):
	FREEGEOPIP_URL = 'http://freegeoip.net/json'
	url = '{}/{}'.format(FREEGEOPIP_URL, ip)

	response = requests.get(url)
	response.raise_for_status()
	out = response.json()

	return out['latitude'], out['longitude']

def home(request):
	return render(request, 'landing.html')

@csrf_exempt
def buy(request):    
	if request.POST:
		location2 = request.POST['address']
		lnglat = location2.split(' ')
		location1 = '%s,%s' % (lnglat[1], lnglat[0])
		sellers = get_sellers(location2)
		return render(request, 'buy.html', { 
			'sellers': sellers,
			'location1': location1,
			'location2': location2 })
	else:
		return render(request, 'buy.html', { 'map_initial': True })

def real_estate(request):
	if request.POST:
		address = request.POST['delivery_address']
		date_time = request.POST['delivery_datetime']

		geolocator = GoogleV3()
		location = geolocator.geocode(address)

		if not location:
			sellers = []
		else:
			sellers = get_sellers_address(location, date_time)
			address = location.address

		return render(request, 'real_estate.html', {
			'initialized': True,
			'address': address,
			'date_time': date_time,
			'sellers': sellers,
		})
	else:
		return render(request, 'real_estate.html', {})

@csrf_exempt
def start_order(request):
	id = request.POST.get('id')
	location = request.POST.get('location')
	distance = request.POST.get('distance')
	address = request.POST.get('address')

	if not address:
		geolocator = Nominatim()
		address = geolocator.reverse(location)

	seller = Seller.objects.get(id=id)
	initial_data = model_to_dict(seller)
	initial_data['address'] = str(address)
	initial_data['unit_price'] = '$'+str(initial_data['unit_price']) 
	# initial_data['address'] = location
	initial_data['distance'] = distance+' miles away'

	form = OrderForm(initial=initial_data)

	return render(request, 'order.html', {
		'form': form, 
		'key': settings.STRIPE_KEYS['PUBLIC_KEY']
	})


def get_tax(address, price):
	'''
	calculate tax from address
	accept only usa now
	Avalara TaxRatesAPI key. Free and limits requests to 15 per minute 
	resources: http://taxratesapi.avalara.com/docs	
	'''
	tax = 0
	address = address.split(',')	
	country = address[-1].strip()
	if country == 'United States of America':
	# if country == 'Canada':
		postal = address[-2].strip()

		key = 'RjCqBdo2dxlGbTNWyo3uxsf8xv+T/teMcaL9TN6DhNy49DmC1nzbJ7QFIxjb6IjTkcrWVxo186CUhB/zs+AC4A=='
		url = 'https://taxrates.api.avalara.com:443/postal?country=%s&postal=%s' % ('usa', postal)

		header = {"Authorization": "AvalaraApiKey "+key}
		res = requests.get(url=url, headers=header)
		res_json = res.json()
		tax = float(res_json.get('totalRate', 0.0))
		tax = int(price * tax / 100) 
	return tax

def charge(request):
	form = OrderForm(request.POST)
	if form.is_valid():
		first_name = form.cleaned_data['first_name']
		seller = Seller.objects.get(first_name=first_name)
		price_in_cents = int(int(seller.unit_price * 100) * float(form.cleaned_data['quantity']))
		card = request.POST.get('stripeToken')
		stripe.api_key = settings.STRIPE_KEYS['API_KEY']
		stripe_account_id = SocialAccount.objects.get(user__id=seller.id, provider='stripe').uid
	
		# tax = get_tax(form.cleaned_data['address'], price_in_cents)	
		tax = 0
		charge = stripe.Charge.create(
			amount=price_in_cents+tax,
			currency="usd",
			source=card,
			destination=stripe_account_id,
			application_fee = int(price_in_cents * seller.app_fee),
			description='Thank you for your purchase!'
		)
		
		sale = Sale()
		sale.seller = seller
		sale.quantity = float(form.cleaned_data['quantity'])
		sale.delivery_address = form.cleaned_data['address']
		sale.buyer_name = form.cleaned_data['buyer_name']
		sale.buyer_phone = form.cleaned_data['buyer_phone']
		sale.charge_id = charge.id
		sale.save()
		
		delivery_datetime = request.POST.get('delivery_datetime_charge')		
		# send email
		email_subject = 'Order Confirmation'
		if delivery_datetime:
			email_body = "Dear %s.\n\nYou've got a new pre order from Customer: %s \nAddress: %s\nPhone Number: %s\nQuantity: %.2f\nDate & Time: %s\nPlease confirm the order and fulfill it.\n\nThank you." % (seller.first_name, sale.buyer_name, sale.delivery_address, sale.buyer_phone, sale.quantity, delivery_datetime)
		else:
			email_body = "Dear %s.\n\nYou've got an order from Customer: %s \nAddress: %s\nPhone Number: %s\nQuantity: %.2f\nPlease confirm the order and fulfill it.\n\nThank you." % (seller.first_name, sale.buyer_name, sale.delivery_address, sale.buyer_phone, sale.quantity)

		print email_body, '@@@@@@@@2'
		send_mail(email_subject, email_body, settings.DEFAULT_FROM_EMAIL, [seller.email], fail_silently=False)
		send_SMS(seller.phone)
		
		return render(request, 'order_success.html', {'seller': seller})
	return render(request, 'order.html', {
		'form': form,
		'key': settings.STRIPE_KEYS['PUBLIC_KEY']
	})

def login(request):
	return render(request, 'login.html')

def about(request):
	# return render(request, 'about.html', {'timezones': pytz.common_timezones})    
	return render(request, 'about.html')    

# login required for creating new seller account
@login_required(login_url='/login/')
def seller(request):
	seller = Seller.objects.get(username=request.user)

	if request.method == 'GET':
		form = SellerForm(initial=model_to_dict(seller))
	else:
		form = SellerForm(request.POST, request.FILES)
		if form.is_valid():         
			seller.first_name = form.cleaned_data['first_name']
			seller.open_hour = form.cleaned_data['open_hour']
			seller.close_hour = form.cleaned_data['close_hour']
			seller.address = form.cleaned_data['address']
			seller.phone = form.cleaned_data['phone']
			seller.radius = form.cleaned_data['radius']
			seller.item = form.cleaned_data['item']
			seller.unit_price = form.cleaned_data['unit_price']
			if form.cleaned_data['picture']:
				seller.picture = form.cleaned_data['picture']
			seller.description = form.cleaned_data['description']
			seller.min_order_amount = form.cleaned_data['min_order_amount']
			seller.permit_number = form.cleaned_data['permit_number']
			seller.permit_exp = form.cleaned_data['permit_exp']
			# seller.license = form.cleaned_data['license']
			seller.operating_days = form.cleaned_data['operating_days']
			seller.estimated_delivery = form.cleaned_data['estimated_delivery']
			seller.save()

			return HttpResponseRedirect('/login/')

	open_hour = seller.open_hour.hour * 60 + seller.open_hour.minute
	close_hour = seller.close_hour.hour * 60 + seller.close_hour.minute

	return render(request, 'seller.html', {'form': form, 'open_hour': open_hour, 'close_hour': close_hour })


def send_SMS(phone_number):
	'''
	send SMS to the seller to confirm the order using twillio
	'''

templates/ajax.html
{% block body %}
{% endblock %}
{% block javascript %}
{% endblock %}

templates/buy.html
<!-- removed extend base as I developed the single landing page on the base.html. I wil need to move this to another sheet-->
{% extends 'base.html' %}
{% load static %} 

{% block meta_main %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css" />

<header class="page-header center-center x-large image-background image-32 no-padding">
	<div class="opacity-5">
		<div class="container v-align-center">
			<div class="row">
				<div class="col-md-12 text-light">
					<div class="nav-style-1 header-transparent-header-space"></div>
				
				<!-- help -->
					<!--<a href="#help" class="btn primary small"><i class="icon-glyph-211"></i><span>Help</span></a>-->

					
						<!-- map below -->					
						<div class="row" id="map_wrapper">
 
							<div class="container v-align-center col-md-12 text-light">
								<h2>Select your location on the map
									<span>then select a seller</span>
								</h2>
							</div>
							
							<div id="mapid" class="container" style="height: 400px"></div>
							
							
							<form method="post">
								{% csrf_token %}
								<input id="id_address" name="address" value="{{ location2 }}" type="hidden">
							</form>
							{% if sellers %}
						<!-- if sellers -->
								<div class="center v-align-center col-md--12 text-light">
									<!-- added fade css -->
									<div class="cta-box-btn" data-nekoanim="fadeInUp" data-nekodelay="200">
										<h2>Select a product below:</h2> 
									</div>
								</div>
						<!-- if sellers then end header here -->

												</div>
											</div>
										</div>
									</div>
								</div>
							</header>	
						<!-- if sellers then begin list of sellers here -->	
							<div class="pt-medium pb-medium light-color">

								<div class="container">
									<div class="row">
										<div class="col-md-8 col-md-offset-2" id="seller_wrapper">
										{% for seller in sellers %}																		
											<section class="slice">
												<div class="ln-doc-example">
													<div class="feature-box media-left">
													<h3>Distance: {{seller.distance.mi|floatformat:2}} miles away</h3>
														<img src="/static/media/{{ seller.picture }}" class="avatar x-large" alt="image">
														<div class="feature-box-content">
															<h2>{{seller.item}}<span>by: {{ seller.first_name }}</span></h2>
															<p>
																{{seller.description}}
															</p>
															<a href="javascript:void(0);" onclick="start_order({{ seller.id }}, {{ seller.distance.mi|floatformat:2 }});" class="btn small primary">Order Now</a>
														</div>
													</div>
												</div>
											</section>
										{% endfor %}												
										</div>
										<div class="col-md-8 col-md-offset-2" id="order_div"></div>
									</div><!-- row -->
								</div><!-- container -->
							</div>								
						<!-- if no sellers the show this message -->
								{% else %}
							 
									<div class="center v-align-center col-md--12 text-light">
										<!-- added fade css -->
										<div class="cta-box-btn" data-nekoanim="fadeInUp" data-nekodelay="200">
											<h2>We want sellers in your area:</h2> 
											<!-- added class for button css -->
											<b><u><a class="btn primary medium ml-xsmall mb-xsmall" href = "/login">Begin Selling Now</a></u></b>
										</div>
									</div>		
									</div>						
		<!-- if no sellers then end header here -->
								</div>
							</div>
						</div>
					</div>
				</header>								
				{% endif %}


	<div class="box no-pb white" id="help">
		<section>
			<h3 class="mt-small">Help</h3>
			<p>
				For accuracy and security, please ensure location services are turned on for your browser and that your browser accepts cookies from this website before loading this page. Your location is used to show you sellers nearby, and cookies are used to ensure a secure check-out process.
			</p>
			<a href="/about" class="btn small primary">How it works</a>
		</section>
	</div>
					
		
{% endblock %}
<!-- end blog formating -->

<!-- javascript for map -->
{% block javascript %}
    <script src="https://checkout.stripe.com/checkout.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js"></script>
	<script>
		{% if map_initial %}
			navigator.geolocation.getCurrentPosition(function(position) {
				$('#id_address').val(position.coords.longitude+' '+position.coords.latitude);
				// console.log(position.coords.longitude+' '+position.coords.latitude);
				window.document.forms[0].submit();    
			}, function(error) {
				if (error.code == 1)
					alert('Please allow Safari to access your location:\n Go to Settings->Privacy->Location Services and toggling Safari to On.');
				else
					alert('Error occurred. Error code: ' + error.code);
			});
		{% endif %}

		var customer_location = '{{ location1 }}';        
		var mymap = L.map('mapid').setView([{{ location1 }}], 11);

		L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZ2V0ZnJlc2hiYWtlZCIsImEiOiJjaXBzbjdoZGUwM3oxZnZtMmltazJ0eHU4In0.B9Vu_0d7ZJlCXfwP5V_s5A', {
			maxZoom: 20,
			attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>',
			id: 'mapbox.streets'
		}).addTo(mymap);

		var currentIcon = L.icon({
			iconUrl: '{% static "img/PIN.png" %}',
			iconSize:     [50, 45], // size of the icon
			iconAnchor:   [13, 35], // point of the icon which will correspond to marker's location
			popupAnchor:  [0, -24]  // point from which the popup should open relative to the iconAnchor
		});

		var marker = L.marker([{{ location1 }}], {icon: currentIcon}).addTo(mymap); 
		  
		// add markers for sellers
		{% for seller in sellers %}
			L.marker([{{ seller.location.y }}, {{ seller.location.x }}]).addTo(mymap).bindPopup('{{ seller.first_name }}');        
		{% endfor %}

		function onMapClick(e) {
			$('#id_address').val(e.latlng.lng+' '+e.latlng.lat);
			customer_location.lat = e.latlng.lat;
			customer_location.lon = e.latlng.lon;

			// update current marker
			mymap.removeLayer(marker); 
			marker = L.marker(e.latlng, {icon: currentIcon}).addTo(mymap).setLatLng(e.latlng);
			
			// execute on load of new clicked location
			window.document.forms[0].submit();    
		}

		mymap.on('click', onMapClick);

		function start_order(seller_id, seller_distance) 
		{
			$.post('/start_order/', 'id='+seller_id+'&location='+customer_location+'&distance='+seller_distance)
			.success(function(data){
			  $('#order_div').html(data);
			});
			$('#map_wrapper').hide();
			$('#seller_wrapper').hide();
			window.scrollTo(0, 0);			
		}

	</script> 

{% endblock %}

templates/landing.html
{% extends 'base.html' %}

{% block body %}
<main id="content">

	<!-- splash screen -->
	<header class="page-header center-center nk-fullscreen image-32 image-background no-padding">
		<div class="mask opacity-6" itemscope itemtype="http://schema.org/WebPage">

			<div class="container v-align-center">
				<div class="row">
					<div class="col-md-12 text-light">
						<div class="nav-style-1 header-transparent-header-space"></div>
						<h1 class="x-large block text-light" data-nekoanim="fadeInUp" data-nekodelay="200" itemprop="mainContentOfPage">Get Fresh Cookies,
							<span class="block pt-small" data-nekoanim="fadeIn" data-nekodelay="800" itemprop="mainContentOfPage">And Other Baked Goods Delivered</span>
						</h1>
						<!-- change scroll link from #news to #buy -->
						<a class="btn primary medium ml-xsmall mb-xsmall" href = "/buy" itemprop="relatedLink">Find Nearby Bakers</a>
						<!--<a href="#buy" class="btn large primary scroll-link" target="_blank">Find Nearby Bakers</a> -->
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- / splash screen -->

<!-- call to action -->
</main>
{% endblock %}





		




templates/order.html
{% extends request.is_ajax|yesno:"ajax.html,base.html" %}

{% block main %}
<header class="page-header center-center large image-background image-32 no-padding">
	<div class="mask opacity-5">
		<div class="container v-align-center">
			<div class="row">
				<div class="col-md-12 text-light">
					<div class="nav-style-1 header-transparent-header-space"></div>
					<div class="row">
						<div class="container v-align-center col-md-12 text-light" id="map_wrapper">
							<h2>Complete the order form below
								<span>then select Pay with Card</span>
							</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>	
{% endblock %}

{% block body %}
	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-8" id="seller_wrapper">
					<h3>Order Information</h3>						
					<section class="slice">
						<div class="ln-doc">
							<div class="feature-box media-left">
							{{ form.errors }}
							<form method="post" class="form-horizontal" role="form" action="/charge/" id="order_form">
								{% csrf_token %}
								<input type="hidden" name="stripeToken" id="stripe_token">
								<input type="hidden" id="id_delivery_datetime_charge" name="delivery_datetime_charge">
							  {% for elem in form %}
							  <div class="form-group">
								<label class="control-label col-sm-3" for="id_{{elem.name}}">{{elem.label}}:</label>
								<div class="col-sm-6">
								{{ elem }}									
								</div>
							  </div>
							  {% endfor %}
							  <div class="form-group">
								<div class="col-sm-offset-2 col-sm-5">
								  <button id="customButton" class="btn large primary">Pay with Card</button>      
								</div>
							  </div>		
							</form>	
							</div>
						</div>	
					</section>
				</div>
			</div>
		</div>
	</section>
		
{% endblock %}		
{% block meta_main %}		
	<div class="box no-pb white" id="help">
		<section>
			<h3 class="mt-small">Help</h3>
			<p>
				Enter your order information in the white boxes and ensure your web browser accepts cookies from this website. Your order information will be sent to the seller for fulfilment. 
			</p>
			<a href="/about" class="btn small primary">How it works</a>
		</section>
	</div>

{% endblock %}					
		
{% block javascript %}
<script src="/static/js/jquery.validate.min.js"></script>
<script src="/static/js/jquery.additional.validate.js"></script>
<script>
  $('#id_quantity').attr('min', {{form.min_order_amount.value}});

  var handler = StripeCheckout.configure({
    key: '{{ key }}',
    locale: 'auto',
    token: function(token) {
      $('#stripe_token').val(token.id);
      $("#order_form").submit();
    }
  });

  $('#customButton').on('click', function(e) {
    var form = $("#order_form");
    form.validate({rules: { buyer_phone: {phone_solo: true}}});
    // Open Checkout with further options:
    if (form.valid()) {
        var quantity = parseFloat($('#id_quantity').val());
        var unit_price = parseFloat($('#id_unit_price').val().substring(1));
        var amount = quantity * unit_price * 100;
        // console.log(amount);
        if ($('#id_delivery_datetime').length > 0)
        	$('#id_delivery_datetime_charge').val($('#id_delivery_datetime').val());

        handler.open({
          name: "Seller: {{form.first_name.value}}",
          description: "Purchase a item",
          currency: "usd",
          amount: amount
        });
    }
    e.preventDefault();
  });

  // Close Checkout on page navigation:
  $(window).on('popstate', function() {
    handler.close();
  });
</script>
{% endblock %}